# Generated by Django 5.2.3 on 2026-04-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_analytics_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="America/New_York",
                help_text="IANA timezone for scheduling digest emails",
                max_length=63,
            ),
        ),
    ]
