# Generated by Django 5.2.1 on 2025-06-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0002_savedsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="agenda_match_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="last_agenda_matched",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="last_fetched",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="last_minutes_matched",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="minutes_match_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
