# Generated by Django 5.2.1 on 2025-06-06 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("municipalities", "0001_initial"),
        (
            "searches",
            "0003_search_agenda_match_json_search_last_agenda_matched_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="search",
            unique_together={("muni", "search_term", "all_results")},
        ),
    ]
