# Generated by Django 5.2.1 on 2025-06-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0004_add_unique_constraint_to_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last notification email was sent",
                null=True,
            ),
        ),
    ]
