# Generated by Django 5.2.8 on 2025-11-22 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("municipalities", "0005_add_last_indexed"),
        ("searches", "0005_add_last_notification_sent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="search",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="has_pending_results",
            field=models.BooleanField(
                default=False,
                help_text="True if there are new results waiting to be sent in digest",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="last_checked",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this saved search was last checked",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="notification_frequency",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate"),
                    ("daily", "Daily Digest"),
                    ("weekly", "Weekly Digest"),
                ],
                default="immediate",
                help_text="How often to send notifications for new results",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="document_type",
            field=models.CharField(
                choices=[("all", "All"), ("agenda", "Agenda"), ("minutes", "Minutes")],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="last_result_count",
            field=models.IntegerField(
                default=0, help_text="Number of pages matched in last search"
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="last_result_page_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of page IDs from last search execution (for change detection)",
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="meeting_name_query",
            field=models.CharField(
                blank=True,
                help_text="Full-text search on meeting names",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="municipalities",
            field=models.ManyToManyField(
                blank=True, related_name="searches", to="municipalities.muni"
            ),
        ),
        migrations.AddField(
            model_name="search",
            name="states",
            field=models.JSONField(
                blank=True, default=list, help_text="List of state codes to filter by"
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="search_term",
            field=models.CharField(
                blank=True,
                help_text="Search query. Empty/null for 'all updates' mode.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="search",
            name="agenda_match_json",
        ),
        migrations.RemoveField(
            model_name="search",
            name="all_results",
        ),
        migrations.RemoveField(
            model_name="search",
            name="last_agenda_matched",
        ),
        migrations.RemoveField(
            model_name="search",
            name="last_minutes_matched",
        ),
        migrations.RemoveField(
            model_name="search",
            name="minutes_match_json",
        ),
        migrations.RemoveField(
            model_name="search",
            name="muni",
        ),
    ]
