# Generated by Django 5.2.3 on 2025-11-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0006_alter_search_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="search",
            name="last_result_page_ids",
        ),
        migrations.AddField(
            model_name="search",
            name="last_checked_for_new_pages",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last check for new pages (for change detection)",
                null=True,
            ),
        ),
    ]
