# Generated by Django 5.2.3 on 2025-11-25 04:51

from django.db import migrations, models


def convert_null_to_empty_string(apps, schema_editor):
    """Convert NULL values to empty strings before removing null=True."""
    Search = apps.get_model("searches", "Search")
    Search.objects.filter(search_term__isnull=True).update(search_term="")
    Search.objects.filter(meeting_name_query__isnull=True).update(meeting_name_query="")


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0007_replace_id_list_with_timestamp"),
    ]

    operations = [
        # Convert existing NULL values to empty strings
        migrations.RunPython(
            convert_null_to_empty_string,
            reverse_code=migrations.RunPython.noop,
        ),
        # Remove null=True from CharField fields (Django best practice)
        migrations.AlterField(
            model_name="search",
            name="meeting_name_query",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full-text search on meeting names",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="search_term",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Search query. Empty string for 'all updates' mode.",
                max_length=500,
            ),
        ),
    ]
