# Generated by Django 5.2.3 on 2025-11-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0008_fix_charfield_null_handling"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="notification_channels",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Channel overrides: {"channels": ["discord", "email"]}',
            ),
        ),
    ]
