# Generated by Django 5.2.3 on 2026-01-27 00:44

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("municipalities", "0005_add_last_indexed"),
        ("searches", "0009_savedsearch_notification_channels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicSearchPage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug (e.g., 'rent' for /topics/rent/)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title (e.g., 'Rent Control Discussions')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description/intro text shown at top of page",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only published pages are visible to public",
                    ),
                ),
                (
                    "lock_search_term",
                    models.BooleanField(
                        default=True,
                        help_text="If true, users cannot modify the search term (only filters)",
                    ),
                ),
                (
                    "allowed_states",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Limit users to only these states (empty = all allowed)",
                    ),
                ),
                (
                    "min_date",
                    models.DateField(
                        blank=True,
                        help_text="Users cannot search before this date",
                        null=True,
                    ),
                ),
                (
                    "max_date",
                    models.DateField(
                        blank=True,
                        help_text="Users cannot search after this date",
                        null=True,
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this page has been viewed"
                    ),
                ),
                (
                    "allowed_municipalities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit users to only these municipalities (empty = all allowed)",
                        related_name="public_search_pages",
                        to="municipalities.muni",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_public_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        help_text="The search configuration for this public page",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_pages",
                        to="searches.search",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Search Page",
                "verbose_name_plural": "Public Search Pages",
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "slug"],
                        name="searches_pu_is_publ_2e33ea_idx",
                    )
                ],
            },
        ),
    ]
