# Generated by Django 5.2.14 on 2026-10-04 23:58

from django.db import migrations, models


def backfill_cutoffs(apps, schema_editor):
    """Seed each saved search's per-user cutoff from its Search's cutoff."""
    SavedSearch = apps.get_model("searches", "SavedSearch")
    for saved_search in SavedSearch.objects.select_related("search").iterator():
        saved_search.last_checked_for_new_pages = (
            saved_search.search.last_checked_for_new_pages
        )
        saved_search.save(update_fields=["last_checked_for_new_pages"])


class Migration(migrations.Migration):
    dependencies = [
        ("searches", "0010_add_public_search_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="last_checked_for_new_pages",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Per-user cutoff: pages created after this time are 'new' "
                    "for this saved search"
                ),
                null=True,
            ),
        ),
        migrations.RunPython(backfill_cutoffs, migrations.RunPython.noop),
    ]
