# Generated by Django 5.2.3 on 2025-11-29 06:26

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0004_meetingdocument_meeting_name_search_vector"),
        ("notebooks", "0002_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotebookEntry",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "meeting_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_entries",
                        to="meetings.meetingpage",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="notebooks.notebook",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="entries", to="notebooks.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notebook Entry",
                "verbose_name_plural": "Notebook Entries",
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notebook", "meeting_page"),
                        name="unique_page_per_notebook",
                    )
                ],
            },
        ),
    ]
