# Generated by Django 5.2.3 on 2025-11-17 19:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("municipalities", "0004_alter_muni_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingDocument",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meeting_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the meeting body (e.g., 'CityCouncil', 'PlanningBoard')",
                        max_length=255,
                    ),
                ),
                ("meeting_date", models.DateField(db_index=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("agenda", "Agenda"), ("minutes", "Minutes")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="municipalities.muni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Document",
                "verbose_name_plural": "Meeting Documents",
                "ordering": ["-meeting_date", "meeting_name"],
            },
        ),
        migrations.CreateModel(
            name="MeetingPage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("page_number", models.IntegerField()),
                ("text", models.TextField(blank=True)),
                (
                    "page_image",
                    models.CharField(
                        blank=True,
                        help_text="Path to the page image (e.g., '/_agendas/CityCouncil/2024-01-02/5.png')",
                        max_length=500,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="meetings.meetingdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Page",
                "verbose_name_plural": "Meeting Pages",
                "ordering": ["document", "page_number"],
            },
        ),
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(
                fields=["municipality", "meeting_name", "meeting_date"],
                name="meetings_muni_name_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(
                fields=["municipality", "document_type"], name="meetings_muni_type_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingdocument",
            unique_together={
                ("municipality", "meeting_name", "meeting_date", "document_type")
            },
        ),
        migrations.AddIndex(
            model_name="meetingpage",
            index=models.Index(
                fields=["document", "page_number"], name="meetings_doc_page_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingpage",
            unique_together={("document", "page_number")},
        ),
    ]
