# Generated by Django 5.2.3 on 2025-11-18 05:45

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meetingpage",
            index=GinIndex(
                fields=["text"],
                name="meetingpage_text_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
