# Generated by Django 5.2.8 on 2025-11-18 20:18

from django.contrib.postgres.operations import UnaccentExtension
from django.contrib.postgres.search import SearchVectorField
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_add_fulltext_search_index"),
    ]

    operations = [
        # Enable unaccent extension for multilingual search
        UnaccentExtension(),
        # Add search_vector column to MeetingPage
        migrations.AddField(
            model_name="meetingpage",
            name="search_vector",
            field=SearchVectorField(null=True),
        ),
        # Populate search_vector with initial data using 'simple' config for multilingual support
        migrations.RunSQL(
            sql="""
                UPDATE meetings_meetingpage
                SET search_vector = to_tsvector('simple', unaccent(coalesce(text, '')));
            """,
            reverse_sql="""
                UPDATE meetings_meetingpage SET search_vector = NULL;
            """,
        ),
        # Create database trigger to auto-update search_vector on INSERT/UPDATE
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION meetings_meetingpage_search_vector_trigger() RETURNS trigger AS $$
                BEGIN
                  NEW.search_vector := to_tsvector('simple', unaccent(coalesce(NEW.text, '')));
                  RETURN NEW;
                END
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER meetings_meetingpage_search_vector_update
                BEFORE INSERT OR UPDATE ON meetings_meetingpage
                FOR EACH ROW
                EXECUTE FUNCTION meetings_meetingpage_search_vector_trigger();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS meetings_meetingpage_search_vector_update ON meetings_meetingpage;
                DROP FUNCTION IF EXISTS meetings_meetingpage_search_vector_trigger();
            """,
        ),
        # Add GIN index on search_vector for fast full-text search
        migrations.RunSQL(
            sql="""
                CREATE INDEX meetingpage_search_vector_idx ON meetings_meetingpage USING GIN (search_vector);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS meetingpage_search_vector_idx;
            """,
        ),
        # Add optimized composite index on MeetingDocument for common filter patterns
        # This supports: municipality, municipality+document_type, municipality+document_type+date_range
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(
                fields=["municipality", "document_type", "meeting_date"],
                name="meetings_muni_type_date_idx",
            ),
        ),
    ]
