# Generated by Django 5.2.8 on 2025-11-19 04:49

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0003_optimize_fulltext_search"),
    ]

    operations = [
        # Add search_vector column to MeetingDocument for meeting name searches
        migrations.AddField(
            model_name="meetingdocument",
            name="meeting_name_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        # Populate meeting_name_search_vector with initial data
        # Includes CamelCase preprocessing (e.g., "CityCouncil" → "City Council")
        migrations.RunSQL(
            sql="""
                UPDATE meetings_meetingdocument
                SET meeting_name_search_vector = to_tsvector(
                    'simple',
                    unaccent(
                        regexp_replace(
                            regexp_replace(
                                coalesce(meeting_name, ''),
                                '([a-z])([A-Z])',
                                '\\1 \\2',
                                'g'
                            ),
                            '([A-Z]+)([A-Z][a-z])',
                            '\\1 \\2',
                            'g'
                        )
                    )
                );
            """,
            reverse_sql="""
                UPDATE meetings_meetingdocument SET meeting_name_search_vector = NULL;
            """,
        ),
        # Create database trigger to auto-update meeting_name_search_vector on INSERT/UPDATE
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION meetings_meetingdocument_search_vector_trigger() RETURNS trigger AS $$
                BEGIN
                  -- Convert CamelCase to spaces for better searchability
                  -- "CityCouncil" → "City Council"
                  -- "PlanningBoard" → "Planning Board"
                  -- "ZBAMeeting" → "ZBA Meeting"
                  NEW.meeting_name_search_vector := to_tsvector(
                    'simple',
                    unaccent(
                      regexp_replace(
                        regexp_replace(
                          coalesce(NEW.meeting_name, ''),
                          '([a-z])([A-Z])',
                          '\\1 \\2',
                          'g'
                        ),
                        '([A-Z]+)([A-Z][a-z])',
                        '\\1 \\2',
                        'g'
                      )
                    )
                  );
                  RETURN NEW;
                END
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER meetings_meetingdocument_search_vector_update
                BEFORE INSERT OR UPDATE ON meetings_meetingdocument
                FOR EACH ROW
                EXECUTE FUNCTION meetings_meetingdocument_search_vector_trigger();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS meetings_meetingdocument_search_vector_update ON meetings_meetingdocument;
                DROP FUNCTION IF EXISTS meetings_meetingdocument_search_vector_trigger();
            """,
        ),
        # Add GIN index on meeting_name_search_vector for fast full-text search
        migrations.RunSQL(
            sql="""
                CREATE INDEX meetingdocument_meeting_name_search_idx ON meetings_meetingdocument USING GIN (meeting_name_search_vector);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS meetingdocument_meeting_name_search_idx;
            """,
        ),
    ]
