# Generated by Django 5.2.3 on 2025-12-31 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0004_meetingdocument_meeting_name_search_vector"),
        ("municipalities", "0005_add_last_indexed"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackfillProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("agenda", "Agenda"), ("minutes", "Minutes")],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("full", "Full"), ("incremental", "Incremental")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "next_cursor",
                    models.TextField(
                        blank=True,
                        help_text="Pagination cursor for resuming backfill",
                        null=True,
                    ),
                ),
                (
                    "force_full_backfill",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True to force full backfill on next run",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if backfill failed",
                        null=True,
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backfill_progress",
                        to="municipalities.muni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backfill Progress",
                "verbose_name_plural": "Backfill Progress",
                "indexes": [
                    models.Index(
                        fields=["status"], name="meetings_ba_status_e21340_idx"
                    ),
                    models.Index(
                        fields=["municipality", "status"],
                        name="meetings_ba_municip_8c0527_idx",
                    ),
                ],
                "unique_together": {("municipality", "document_type")},
            },
        ),
    ]
