# Generated by Django 5.2.3 on 2026-01-25 04:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0005_backfillprogress"),
        ("municipalities", "0005_add_last_indexed"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackfillJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("agenda", "Agenda"), ("minutes", "Minutes")],
                        help_text="Type of document being backfilled (agenda or minutes)",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "last_cursor",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Pagination cursor to resume from if interrupted",
                    ),
                ),
                (
                    "pages_fetched",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of page records fetched from API",
                    ),
                ),
                (
                    "pages_created",
                    models.IntegerField(
                        default=0, help_text="Number of new MeetingPage records created"
                    ),
                ),
                (
                    "pages_updated",
                    models.IntegerField(
                        default=0,
                        help_text="Number of existing MeetingPage records updated",
                    ),
                ),
                (
                    "errors_encountered",
                    models.IntegerField(
                        default=0,
                        help_text="Number of errors encountered during backfill",
                    ),
                ),
                (
                    "expected_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected total page count from API metadata",
                        null=True,
                    ),
                ),
                (
                    "actual_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Actual page count in local database after backfill",
                        null=True,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when verification was performed",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last error message encountered",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts for this job"
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backfill_jobs",
                        to="municipalities.muni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backfill Job",
                "verbose_name_plural": "Backfill Jobs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["municipality", "document_type", "status"],
                        name="backfill_muni_type_status_idx",
                    )
                ],
            },
        ),
    ]
