# Generated by Django 5.2.3 on 2026-01-27 23:04

from django.db import migrations


class Migration(migrations.Migration):
    """
    Add composite index to optimize search queries.

    This migration adds a covering index on MeetingPage that includes both
    document_id and search_vector. This optimizes the common query pattern
    where we filter by full-text search and then join to the document table
    for municipality/state/date filters.

    PostgreSQL's INCLUDE clause allows the index to "cover" queries that need
    both the indexed column (document_id) and additional columns (search_vector)
    without having to visit the heap table.

    IMPORTANT: This migration uses CREATE INDEX CONCURRENTLY which:
    - Does NOT lock the table during index creation
    - Allows normal read/write operations to continue
    - Takes approximately 5-15 minutes for 12 million rows
    - Requires atomic=False to run outside a transaction

    If index creation fails partway through, you may need to manually drop the
    invalid index before re-running:
        DROP INDEX CONCURRENTLY IF EXISTS meetingpage_doc_search_covering_idx;
    """

    dependencies = [
        ("meetings", "0006_backfilljob"),
    ]

    # REQUIRED: atomic=False allows CREATE INDEX CONCURRENTLY to run outside transaction
    atomic = False

    operations = [
        # Create composite index with INCLUDE to optimize search + filter queries
        # Uses CONCURRENTLY to avoid locking the table (safe for production)
        migrations.RunSQL(
            sql="""
                CREATE INDEX CONCURRENTLY IF NOT EXISTS meetingpage_doc_search_covering_idx
                ON meetings_meetingpage (document_id)
                INCLUDE (search_vector);
            """,
            reverse_sql="""
                DROP INDEX CONCURRENTLY IF EXISTS meetingpage_doc_search_covering_idx;
            """,
        ),
    ]
