# Generated by Django 5.2.3 on 2026-01-27 23:04

from django.db import migrations


class Migration(migrations.Migration):
    """
    Add composite index to optimize search queries.

    This migration adds a covering index on MeetingPage that includes both
    document_id and search_vector. This optimizes the common query pattern
    where we filter by full-text search and then join to the document table
    for municipality/state/date filters.

    PostgreSQL's INCLUDE clause allows the index to "cover" queries that need
    both the indexed column (document_id) and additional columns (search_vector)
    without having to visit the heap table.

    Note: Cannot use CONCURRENTLY because it requires running outside a transaction,
    and Django migrations run inside transactions by default.
    """

    dependencies = [
        ("meetings", "0006_backfilljob"),
    ]

    operations = [
        # Create composite index with INCLUDE to optimize search + filter queries
        # This uses PostgreSQL-specific INCLUDE syntax for covering indexes
        # Note: Using regular CREATE INDEX (not CONCURRENTLY) to work within migration transactions
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS meetingpage_doc_search_covering_idx
                ON meetings_meetingpage (document_id)
                INCLUDE (search_vector);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS meetingpage_doc_search_covering_idx;
            """,
        ),
    ]
