# Generated by Django 5.2.3 on 2026-01-27 23:04

from django.db import migrations


class Migration(migrations.Migration):
    """
    Add index to optimize search query joins.

    This migration adds an index on MeetingPage.document_id to optimize
    the common query pattern where we filter by full-text search and then
    join to the document table for municipality/state/date filters.

    Note: Originally attempted to use INCLUDE (search_vector) for a covering
    index, but that exceeds PostgreSQL's 8191 byte index row limit since
    search_vector can be very large for long documents. A simple index on
    document_id is sufficient for join optimization.

    IMPORTANT: This migration uses CREATE INDEX CONCURRENTLY which:
    - Does NOT lock the table during index creation
    - Allows normal read/write operations to continue
    - Takes approximately 3-8 minutes for 12 million rows
    - Requires atomic=False to run outside a transaction

    If index creation fails partway through, you may need to manually drop the
    invalid index before re-running:
        DROP INDEX CONCURRENTLY IF EXISTS meetingpage_document_search_idx;

    Note: There's already an index on document_id from the foreign key, but
    this creates an additional index specifically optimized for our search
    query pattern. We may be able to remove this if the existing FK index
    proves sufficient.
    """

    dependencies = [
        ("meetings", "0006_backfilljob"),
    ]

    # REQUIRED: atomic=False allows CREATE INDEX CONCURRENTLY to run outside transaction
    atomic = False

    operations = [
        # This migration is now a no-op because:
        # 1. The FK index on document_id (meetings_meetingpage_document_id_5d2b8440) is sufficient
        # 2. Attempting INCLUDE (search_vector) exceeds PostgreSQL's 8191 byte limit
        # 3. The other optimizations (JOIN, filter reordering, rank caching) provide the main gains
        migrations.RunSQL(
            sql="-- No-op: FK index on document_id is sufficient for join optimization",
            reverse_sql="-- No-op",
        ),
    ]
