# Generated by Django 5.2.8 on 2026-02-06

from django.db import migrations


class Migration(migrations.Migration):
    """
    Originally: Rebuild GIN indexes with fastupdate=off.

    This migration has been converted to a no-op because the DROP/CREATE INDEX
    operations (without CONCURRENTLY) acquire ACCESS EXCLUSIVE locks that block
    all reads/writes for 15-30+ minutes on the 12M row meetingpage table.
    In production this caused a 12+ hour deploy hang.

    The index optimization should be applied manually with CONCURRENTLY
    during a maintenance window:

        DROP INDEX CONCURRENTLY IF EXISTS meetingpage_search_vector_idx;
        CREATE INDEX CONCURRENTLY meetingpage_search_vector_idx
            ON meetings_meetingpage USING GIN (search_vector) WITH (fastupdate=off);

        DROP INDEX CONCURRENTLY IF EXISTS meetingdocument_meeting_name_search_idx;
        CREATE INDEX CONCURRENTLY meetingdocument_meeting_name_search_idx
            ON meetings_meetingdocument USING GIN (meeting_name_search_vector)
            WITH (fastupdate=off);
    """

    dependencies = [
        ("meetings", "0007_add_composite_index_for_search"),
    ]

    operations = [
        # No-op: see docstring above
    ]
