# Generated by Django 5.2.8 on 2026-02-06

from django.db import migrations


class Migration(migrations.Migration):
    """
    Optimize GIN indexes for full-text search by disabling fastupdate.

    Problem: GIN indexes with fastupdate=True (default) accumulate a "pending list"
    of new entries that must be scanned on every query and periodically merged,
    causing unpredictable latency spikes of 465ms-3,155ms (per GitLab case study).

    Solution: Rebuild indexes with fastupdate=off for consistent query performance.
    This trades slightly slower inserts for dramatically better read performance,
    which is the right tradeoff for a read-heavy search workload.

    **PRODUCTION DEPLOYMENT WARNING**:

    This migration drops and recreates GIN indexes WITHOUT using CONCURRENTLY,
    which means it will acquire ACCESS EXCLUSIVE locks on the tables. This will
    BLOCK all reads and writes to meetings_meetingpage and meetings_meetingdocument
    during index rebuilds.

    **Estimated duration on 12M rows**: 15-30 minutes with maintenance_work_mem=2GB

    **RECOMMENDED PRODUCTION APPROACH**:
    1. Skip this migration (comment out or use --fake)
    2. Run these commands manually during a maintenance window:

       -- For meetings_meetingpage (this is the critical one - 12M+ rows)
       DROP INDEX CONCURRENTLY IF EXISTS meetingpage_search_vector_idx;
       CREATE INDEX CONCURRENTLY meetingpage_search_vector_idx
           ON meetings_meetingpage USING GIN (search_vector) WITH (fastupdate=off);

       -- For meetings_meetingdocument (smaller table, faster)
       DROP INDEX CONCURRENTLY IF EXISTS meetingdocument_meeting_name_search_idx;
       CREATE INDEX CONCURRENTLY meetingdocument_meeting_name_search_idx
           ON meetings_meetingdocument USING GIN (meeting_name_search_vector) WITH (fastupdate=off);

    **For development/staging**: This migration is safe to run normally.
    """

    dependencies = [
        ("meetings", "0007_add_composite_index_for_search"),
    ]

    operations = [
        # Drop existing GIN index on MeetingPage.search_vector
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS meetingpage_search_vector_idx;
            """,
            reverse_sql="""
                CREATE INDEX meetingpage_search_vector_idx
                ON meetings_meetingpage USING GIN (search_vector);
            """,
        ),
        # Recreate with fastupdate=off
        migrations.RunSQL(
            sql="""
                CREATE INDEX meetingpage_search_vector_idx
                ON meetings_meetingpage
                USING GIN (search_vector)
                WITH (fastupdate=off);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS meetingpage_search_vector_idx;
            """,
        ),
        # Drop existing GIN index on MeetingDocument.meeting_name_search_vector
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS meetingdocument_meeting_name_search_idx;
            """,
            reverse_sql="""
                CREATE INDEX meetingdocument_meeting_name_search_idx
                ON meetings_meetingdocument USING GIN (meeting_name_search_vector);
            """,
        ),
        # Recreate with fastupdate=off
        migrations.RunSQL(
            sql="""
                CREATE INDEX meetingdocument_meeting_name_search_idx
                ON meetings_meetingdocument
                USING GIN (meeting_name_search_vector)
                WITH (fastupdate=off);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS meetingdocument_meeting_name_search_idx;
            """,
        ),
    ]
