# Generated by Django 5.2.8 on 2026-02-06

from django.db import migrations


class Migration(migrations.Migration):
    """
    Tune autovacuum settings for meetings_meetingpage table.

    Problem: Default autovacuum_vacuum_scale_factor = 0.2 means vacuum only
    triggers after 20% of rows become dead tuples. For a 12M row table, that's
    2.4M dead tuples - far too much bloat accumulates before cleanup.

    Solution: Lower the scale factor to trigger more frequent vacuums, preventing
    bloat and keeping indexes efficient. Settings optimized for high-churn FTS table.

    Impact: More frequent but smaller vacuum operations, maintaining consistent
    query performance as data changes.
    """

    dependencies = [
        ("meetings", "0008_optimize_gin_indexes"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE meetings_meetingpage SET (
                    autovacuum_vacuum_scale_factor = 0.02,
                    autovacuum_analyze_scale_factor = 0.01,
                    autovacuum_vacuum_cost_limit = 2000,
                    autovacuum_vacuum_cost_delay = 2
                );
            """,
            reverse_sql="""
                ALTER TABLE meetings_meetingpage RESET (
                    autovacuum_vacuum_scale_factor,
                    autovacuum_analyze_scale_factor,
                    autovacuum_vacuum_cost_limit,
                    autovacuum_vacuum_cost_delay
                );
            """,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE meetings_meetingdocument SET (
                    autovacuum_vacuum_scale_factor = 0.02,
                    autovacuum_analyze_scale_factor = 0.01,
                    autovacuum_vacuum_cost_limit = 2000,
                    autovacuum_vacuum_cost_delay = 2
                );
            """,
            reverse_sql="""
                ALTER TABLE meetings_meetingdocument RESET (
                    autovacuum_vacuum_scale_factor,
                    autovacuum_analyze_scale_factor,
                    autovacuum_vacuum_cost_limit,
                    autovacuum_vacuum_cost_delay
                );
            """,
        ),
    ]
