# Generated by Django 5.2.14 on 2026-08-20 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0009_tune_autovacuum"),
        ("municipalities", "0005_add_last_indexed"),
    ]

    operations = [
        # Drop triggers and functions that reference columns about to be removed
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS meetings_meetingdocument_search_vector_update ON meetings_meetingdocument;
                DROP FUNCTION IF EXISTS meetings_meetingdocument_search_vector_trigger();
                DROP TRIGGER IF EXISTS meetings_meetingpage_search_vector_update ON meetings_meetingpage;
                DROP FUNCTION IF EXISTS meetings_meetingpage_search_vector_trigger();
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Drop old GIN indexes that reference the columns
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS meetingpage_search_vector_idx;
                DROP INDEX IF EXISTS meetingdocument_meeting_name_search_idx;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveIndex(
            model_name="meetingpage",
            name="meetings_doc_page_idx",
        ),
        migrations.RemoveIndex(
            model_name="meetingpage",
            name="meetingpage_text_gin_idx",
        ),
        migrations.RemoveField(
            model_name="meetingdocument",
            name="meeting_name_search_vector",
        ),
        migrations.RemoveField(
            model_name="meetingpage",
            name="search_vector",
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="document_type",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="legacy_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="meeting_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="meeting_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="municipality",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="municipalities.muni",
            ),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="municipality_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="municipality_subdomain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="meetingpage",
            name="state",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
