# Generated by Django 5.2.1 on 2025-06-04 04:42

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Muni",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subdomain", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=10)),
                ("country", models.CharField(default="USA", max_length=50)),
                ("kind", models.CharField(max_length=50)),
                ("pages", models.IntegerField(default=0)),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("popup_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Municipality",
                "verbose_name_plural": "Municipalities",
                "ordering": ["name"],
            },
        ),
    ]
