# Generated by Django 5.2.1 on 2025-06-10 20:02

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("municipalities", "0002_alter_muni_country_alter_muni_kind_alter_muni_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muni",
            name="country",
            field=django_countries.fields.CountryField(default="US", max_length=255),
        ),
    ]
