# Generated by Django 5.2.1 on 2025-06-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("municipalities", "0003_alter_muni_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muni",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
