# Generated by Django 5.2.3 on 2025-11-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("municipalities", "0004_alter_muni_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="muni",
            name="last_indexed",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when meeting documents were last indexed for this municipality",
                null=True,
            ),
        ),
    ]
